version: '2.0'

services:
  db:
    image: mysql:5.7
    container_name: landlord_data
    restart: always
    ports:
        - "3333:3306"
    environment:
      MYSQL_DATABASE: landlord
      MYSQL_USER: landlord
      MYSQL_PASSWORD: hackupstate
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
