web_server:
  host: '0.0.0.0'
  port: 5055
  debug: True
  flask_app_name: 'landlord-server'
  url_prefix: '/api/v1'

database:
  host: 'localhost'
  user: 'landlord'
  password: 'hackupstate'
  port: 3333
  database: 'landlord'

